package vista;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class HistorialPanel extends javax.swing.JPanel {

    public HistorialPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager1 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("RetoSofkaPU").createEntityManager();
        jScrollPane1 = new javax.swing.JScrollPane();
        partidasJT = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        partidasJT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id Partida", "Nombre Jugador", "Acumulado", "Ronda Alcanzada"
            }
        ));
        jScrollPane1.setViewportView(partidasJT);

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Se vacía la tabla para no duplicar los datos y extender la tabla.
        DefaultTableModel cleanModel = (DefaultTableModel)partidasJT.getModel();
        cleanModel.setRowCount(0);
        
        try{
            //Se crea la conección
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb", "root", "");
            Statement st = con.createStatement();
            String sql = "select * from partida";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                
                String id = String.valueOf(rs.getInt("idpartida"));
                String nombre = rs.getString("nombreJugador");
                String acumulado = String.valueOf(rs.getInt("acumulado"));
                String ronda = String.valueOf(rs.getInt("rondaAlcanzada"));
                
                String tbData[] = {id, nombre, acumulado, ronda};
                DefaultTableModel tb1Model = (DefaultTableModel)partidasJT.getModel();
                
                tb1Model.addRow(tbData);
                
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ha ocurrido la excepción " + e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManager1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable partidasJT;
    // End of variables declaration//GEN-END:variables
}
